"use client";

import "./globals.css";
import Navbar from "../_lib/navbar/page.jsx";
import Footer from "../_lib/footer/page.jsx";
import { usePathname } from "next/navigation";
import { CartProvider } from "@/context/CartContext";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();

  // If on /login and /register skip layout
  if (pathname === "/login" || pathname === "/register") {
    return <>{children}</>;
  }

  return (
    <>
      <html lang="en">
        <body>
          <CartProvider>
            <Navbar />
            {children}
            <Footer />
          </CartProvider>
        </body>
      </html>
    </>
  );
}
